### ISSUE TITLE
Minified version doesn't work

### ISSUE THREAD

**Issue by barmalejj** [f-xyz/ng-repeat-fast#1]
We've tried to use this module in our project and it works really great, but there are some issues with minified version. We tried to use minified version from Your repo and tried to minify ourselves. Result is always the same - in such example:
```
<li ng-repeat-fast="item in items"></li>
```
 item always is undefined. Trying to reproduce on [plunker](http://plnkr.co/edit/jIVow269dJqWFcLcucPY?p=preview) I've got something different: https://docs.angularjs.org/error/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20ngRepeatFastDirective, but still it's an error with minified and success with full version.

**Comment by f-xyz** [comment]
The issue has been fixed.
Thank you for the reporting!
